apiVersion: 1

datasources:
  - name: MongoDB
    type: grafana-mongodb-datasource
    access: proxy
    url: mongodb://mongodb:27017
    jsonData:
      database: learning_platform
    isDefault: true
    editable: true
